// Code generated by Slice Machine. DO NOT EDIT.

import Imagecontainer from './Imagecontainer/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	imagecontainer: Imagecontainer,
	rich_text: RichText
};
