// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = ImagecontainerSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
	/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *Imagecontainer → Primary*
 */
export interface ImagecontainerSliceDefaultPrimary {
	/**
	 * images field in *Imagecontainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: imagecontainer.primary.images
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	images: prismic.ImageField<never>;

	/**
	 * Name field in *Imagecontainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: imagecontainer.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * bio field in *Imagecontainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: imagecontainer.primary.bio
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	bio: prismic.KeyTextField;

	/**
	 * Github field in *Imagecontainer → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: imagecontainer.primary.github
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	github: prismic.LinkField;

	/**
	 * highlights field in *Imagecontainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: imagecontainer.primary.highlights
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	highlights: prismic.ImageField<never>;
}

/**
 * Default variation for Imagecontainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagecontainerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImagecontainerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Imagecontainer*
 */
type ImagecontainerSliceVariation = ImagecontainerSliceDefault;

/**
 * Imagecontainer Shared Slice
 *
 * - **API ID**: `imagecontainer`
 * - **Description**: Imagecontainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImagecontainerSlice = prismic.SharedSlice<
	'imagecontainer',
	ImagecontainerSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			ImagecontainerSlice,
			ImagecontainerSliceDefaultPrimary,
			ImagecontainerSliceVariation,
			ImagecontainerSliceDefault
		};
	}
}
